// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFIQG4oIFpCZ-NDZz8Q4svlQ7OYWwb6Oo',
    appId: '1:119354121565:web:6f7720da12ff614995dcb4',
    messagingSenderId: '119354121565',
    projectId: 'guftagu-82262',
    authDomain: 'guftagu-82262.firebaseapp.com',
    storageBucket: 'guftagu-82262.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjiAt1G5yA9GQu1rEmVAuOG5cgAqdinU',
    appId: '1:119354121565:android:3c75625ae32bdee195dcb4',
    messagingSenderId: '119354121565',
    projectId: 'guftagu-82262',
    storageBucket: 'guftagu-82262.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfwwMsJ3lTMgQvBvG7wfJ6kt8wZ4Kt5Gg',
    appId: '1:119354121565:ios:dec7f3c1874bc21395dcb4',
    messagingSenderId: '119354121565',
    projectId: 'guftagu-82262',
    storageBucket: 'guftagu-82262.appspot.com',
    iosClientId: '119354121565-fu22n8mu1nk91fr7s23o1832nt144fal.apps.googleusercontent.com',
    iosBundleId: 'com.example.guftagu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfwwMsJ3lTMgQvBvG7wfJ6kt8wZ4Kt5Gg',
    appId: '1:119354121565:ios:1313fc0eecd90e9095dcb4',
    messagingSenderId: '119354121565',
    projectId: 'guftagu-82262',
    storageBucket: 'guftagu-82262.appspot.com',
    iosClientId: '119354121565-uiqqgi7v8ueo1g7g0oljiu6fqa9n72si.apps.googleusercontent.com',
    iosBundleId: 'com.example.guftagu.RunnerTests',
  );
}
